server:
  port: 8070

spring:
  application:
    name: spring-cloud-alibaba-server-provider

  cloud:
    nacos:
      discovery:
        #服务注册中心地址
        server-addr: localhost:8848

#暴露监控健康点
management:
  endpoints:
    web:
      exposure:
        include: "*"