server:
  port: 8081

spring:
  application:
    name: spring-cloud-alibaba-sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #sentinel-dashboard的地址
    sentinel:
      transport:
        dashboard: localhost:8888
#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露监控健康点
management:
  endpoints:
    web:
      exposure:
        include: "*"
